# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS zlib libjpeg-turbo libtiff libwebp libopenjp2 libpng IlmImf libprotobuf ittnotify ade ocv.3rdparty.flatbuffers ocv.3rdparty.dshow ocv.3rdparty.msmf ocv.3rdparty.ffmpeg ocv.3rdparty.obsensor ocv.3rdparty.win32ui opencv_world opencv_img_hash)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target zlib
add_library(zlib STATIC IMPORTED)

# Create imported target libjpeg-turbo
add_library(libjpeg-turbo STATIC IMPORTED)

# Create imported target libtiff
add_library(libtiff STATIC IMPORTED)

set_target_properties(libtiff PROPERTIES
  INTERFACE_LINK_LIBRARIES "zlib"
)

# Create imported target libwebp
add_library(libwebp STATIC IMPORTED)

# Create imported target libopenjp2
add_library(libopenjp2 STATIC IMPORTED)

set_target_properties(libopenjp2 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OPJ_STATIC"
)

# Create imported target libpng
add_library(libpng STATIC IMPORTED)

set_target_properties(libpng PROPERTIES
  INTERFACE_LINK_LIBRARIES "zlib"
)

# Create imported target IlmImf
add_library(IlmImf STATIC IMPORTED)

set_target_properties(IlmImf PROPERTIES
  INTERFACE_LINK_LIBRARIES "zlib"
)

# Create imported target libprotobuf
add_library(libprotobuf STATIC IMPORTED)

set_target_properties(libprotobuf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-src/3rdparty/protobuf/src"
)

# Create imported target ittnotify
add_library(ittnotify STATIC IMPORTED)

# Create imported target ade
add_library(ade STATIC IMPORTED)

set_target_properties(ade PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/ade/ade-0.1.2e/sources/ade/include"
)

# Create imported target ocv.3rdparty.flatbuffers
add_library(ocv.3rdparty.flatbuffers INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.flatbuffers PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_FLATBUFFERS=1"
  INTERFACE_INCLUDE_DIRECTORIES "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-src/3rdparty/flatbuffers/include"
)

# Create imported target ocv.3rdparty.dshow
add_library(ocv.3rdparty.dshow INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.dshow PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_DSHOW"
)

# Create imported target ocv.3rdparty.msmf
add_library(ocv.3rdparty.msmf INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.msmf PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_MSMF;HAVE_MSMF_DXVA"
)

# Create imported target ocv.3rdparty.ffmpeg
add_library(ocv.3rdparty.ffmpeg INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.ffmpeg PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_FFMPEG_WRAPPER"
)

# Create imported target ocv.3rdparty.obsensor
add_library(ocv.3rdparty.obsensor INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.obsensor PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_OBSENSOR;HAVE_OBSENSOR_MSMF"
)

# Create imported target ocv.3rdparty.win32ui
add_library(ocv.3rdparty.win32ui INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.win32ui PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_WIN32UI"
  INTERFACE_LINK_LIBRARIES "user32;gdi32"
)

# Create imported target opencv_world
add_library(opencv_world STATIC IMPORTED)

set_target_properties(opencv_world PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:cudart_static.lib>;\$<LINK_ONLY:nppc.lib>;\$<LINK_ONLY:nppial.lib>;\$<LINK_ONLY:nppicc.lib>;\$<LINK_ONLY:nppidei.lib>;\$<LINK_ONLY:nppif.lib>;\$<LINK_ONLY:nppig.lib>;\$<LINK_ONLY:nppim.lib>;\$<LINK_ONLY:nppist.lib>;\$<LINK_ONLY:nppisu.lib>;\$<LINK_ONLY:nppitc.lib>;\$<LINK_ONLY:npps.lib>;\$<LINK_ONLY:cublas.lib>;\$<LINK_ONLY:cudnn.lib>;\$<LINK_ONLY:cufft.lib>;-LIBPATH:\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/lib/x64\";\$<LINK_ONLY:cublas.lib>;\$<LINK_ONLY:cufft.lib>;\$<LINK_ONLY:ocv.3rdparty.flatbuffers>;\$<LINK_ONLY:libprotobuf>;\$<LINK_ONLY:libjpeg-turbo>;\$<LINK_ONLY:libwebp>;\$<LINK_ONLY:libpng>;\$<LINK_ONLY:libtiff>;\$<LINK_ONLY:libopenjp2>;\$<LINK_ONLY:IlmImf>;\$<LINK_ONLY:zlib>;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/lib/x64/cuda.lib;\$<LINK_ONLY:comctl32>;\$<LINK_ONLY:gdi32>;\$<LINK_ONLY:ole32>;\$<LINK_ONLY:setupapi>;\$<LINK_ONLY:ws2_32>;\$<LINK_ONLY:zlib>;\$<LINK_ONLY:ittnotify>;\$<LINK_ONLY:ocv.3rdparty.dshow>;\$<LINK_ONLY:ocv.3rdparty.msmf>;\$<LINK_ONLY:ocv.3rdparty.ffmpeg>;\$<LINK_ONLY:ocv.3rdparty.obsensor>;\$<LINK_ONLY:ocv.3rdparty.win32ui>;\$<LINK_ONLY:ade>;\$<LINK_ONLY:ittnotify>;\$<LINK_ONLY:wsock32>;\$<LINK_ONLY:ws2_32>;\$<LINK_ONLY:ocv.3rdparty.msmf>;\$<LINK_ONLY:cudart_static.lib>;\$<LINK_ONLY:nppc.lib>;\$<LINK_ONLY:nppial.lib>;\$<LINK_ONLY:nppicc.lib>;\$<LINK_ONLY:nppidei.lib>;\$<LINK_ONLY:nppif.lib>;\$<LINK_ONLY:nppig.lib>;\$<LINK_ONLY:nppim.lib>;\$<LINK_ONLY:nppist.lib>;\$<LINK_ONLY:nppisu.lib>;\$<LINK_ONLY:nppitc.lib>;\$<LINK_ONLY:npps.lib>"
)

# Create imported target opencv_img_hash
add_library(opencv_img_hash STATIC IMPORTED)

set_target_properties(opencv_img_hash PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_world;opencv_world;\$<LINK_ONLY:cudart_static.lib>;\$<LINK_ONLY:nppc.lib>;\$<LINK_ONLY:nppial.lib>;\$<LINK_ONLY:nppicc.lib>;\$<LINK_ONLY:nppidei.lib>;\$<LINK_ONLY:nppif.lib>;\$<LINK_ONLY:nppig.lib>;\$<LINK_ONLY:nppim.lib>;\$<LINK_ONLY:nppist.lib>;\$<LINK_ONLY:nppisu.lib>;\$<LINK_ONLY:nppitc.lib>;\$<LINK_ONLY:npps.lib>;\$<LINK_ONLY:cublas.lib>;\$<LINK_ONLY:cudnn.lib>;\$<LINK_ONLY:cufft.lib>;-LIBPATH:\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/lib/x64\";\$<LINK_ONLY:cudart_static.lib>;\$<LINK_ONLY:nppc.lib>;\$<LINK_ONLY:nppial.lib>;\$<LINK_ONLY:nppicc.lib>;\$<LINK_ONLY:nppidei.lib>;\$<LINK_ONLY:nppif.lib>;\$<LINK_ONLY:nppig.lib>;\$<LINK_ONLY:nppim.lib>;\$<LINK_ONLY:nppist.lib>;\$<LINK_ONLY:nppisu.lib>;\$<LINK_ONLY:nppitc.lib>;\$<LINK_ONLY:npps.lib>"
)

# Import target "zlib" for configuration "Release"
set_property(TARGET zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(zlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/zlib.lib"
  )

# Import target "libjpeg-turbo" for configuration "Release"
set_property(TARGET libjpeg-turbo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libjpeg-turbo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libjpeg-turbo.lib"
  )

# Import target "libtiff" for configuration "Release"
set_property(TARGET libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libtiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libtiff.lib"
  )

# Import target "libwebp" for configuration "Release"
set_property(TARGET libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libwebp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libwebp.lib"
  )

# Import target "libopenjp2" for configuration "Release"
set_property(TARGET libopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libopenjp2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libopenjp2.lib"
  )

# Import target "libpng" for configuration "Release"
set_property(TARGET libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libpng.lib"
  )

# Import target "IlmImf" for configuration "Release"
set_property(TARGET IlmImf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IlmImf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/IlmImf.lib"
  )

# Import target "libprotobuf" for configuration "Release"
set_property(TARGET libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/libprotobuf.lib"
  )

# Import target "ittnotify" for configuration "Release"
set_property(TARGET ittnotify APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ittnotify PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/ittnotify.lib"
  )

# Import target "ade" for configuration "Release"
set_property(TARGET ade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ade PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/3rdparty/lib/ade.lib"
  )

# Import target "opencv_world" for configuration "Release"
set_property(TARGET opencv_world APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_world PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/lib/opencv_world4140.lib"
  )

# Import target "opencv_img_hash" for configuration "Release"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "H:/0000_CODE/01_collider_pyo/juce/build-opencv-cuda/_deps/opencv-build/lib/opencv_img_hash4140.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
